#!/usr/bin/ruby
begin
	puts "I'll be run."           #=> Programm at this block run...
	raise "oops!"                 #=> For this moment...
	puts "I'll be skipped."       #=> We don't go forward
rescue                          #=> But control is transferred here...
  puts "Rescued an exception!"
end                             #=> Code move forward after block,but if- 

#-we find solution of this problem...
